#!/bin/bash

echo "========================================="
echo "  飞书多维表格 ID 获取指南"
echo "========================================="
echo ""
echo "1. 打开飞书多维表格"
echo "2. 从浏览器 URL 获取信息："
echo ""
echo "   URL 格式示例:"
echo "   https://xxx.feishu.cn/base/APP_TOKEN/XXXXX?table=TABLE_ID"
echo ""
echo "   或者:"
echo "   https://xxx.feishu.cn/base/bascnXXXXXX/XXXXX"
echo ""
echo "3. APP_TOKEN 是 URL 中的第一段 ID"
echo "   例如: bascnXXXXXX 或 appXXXXXX"
echo ""
echo "4. TABLE_ID 获取方法："
echo "   方法一 - 从 URL 查找:"
echo "   在 URL 中查找 table=xxxxx 参数"
echo ""
echo "   方法二 - 浏览器控制台:"
echo "   打开多维表格后按 F12，在控制台执行:"
echo "   window.activeApp.getTableId()"
echo ""
echo "========================================="
echo ""
echo "获取到信息后，填入 .env 文件:"
echo ""
echo "FEISHU_APP_TOKEN=你的app_token"
echo "FEISHU_TABLE_ID=你的table_id"
echo ""
echo "========================================="
